Repository gillhad/ea_sports_vu, pull requests merged in 2024-06, with the labels that each got.

#4 add intl closes #3
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/modules/core/core.module.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: enhancement

#5 Test/test1
  .gitignore
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/modules/core/core.module.ts
  src/app/services/breadcrumbs.service.spec.ts
  src/app/services/breadcrumbs.service.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: test

#6 test2
  src/app/components/footer/footer.component.html
Labels: test

#8 test4
  src/app/components/footer/footer.component.html
Labels: test

#9 test 6
  src/app/components/header/header.component.html
Labels: test

#10 test5
  src/app/components/header/header.component.html
Labels: test

#13 create models closes #12
  src/app/app-routing.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/interfaces/player.interface.ts
  src/app/interfaces/request-players.ts
  src/app/interfaces/stats.interface.ts
  src/app/models/player.spec.ts
  src/app/models/player.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/request-player.service.spec.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.ts
  src/assets/players.json
Labels: enhancement

#16 added structure and styles header closes #14
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/services/lenguage.service.ts
  src/app/styles/variables.styles.scss
  src/assets/ea-fifa.svg
  src/assets/england-flag.png
  src/assets/spain-flag.png
  src/index.html
  src/styles.scss
Labels: enhancement

#17 added structure and styles footer component closes #15
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/styles/variables.styles.scss
Labels: enhancement

#20 Feature/player card
  src/app/components/footer/footer.component.scss
  src/app/components/header/header.component.scss
  src/app/components/player-card/player-card.component.html
  src/app/components/player-card/player-card.component.scss
  src/app/components/player-card/player-card.component.ts
  src/app/views/home/home.component.html
  src/app/views/home/home.component.scss
  src/app/views/home/home.component.ts
  src/assets/players.json
Labels: duplicate

#22 add navigation to profile
  src/app/components/player-card/player-card.component.ts
  src/app/components/stats/stats.component.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.ts
Labels: enhancement

#24 Features/add video view
  src/app/app.module.ts
  src/app/components/player-card/player-card.component.ts
  src/app/pipes/safe-url.pipe.spec.ts
  src/app/pipes/safe-url.pipe.ts
  src/app/styles/mixin.styles.scss
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.scss
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.html
  src/app/views/video-details/video-details.component.scss
  src/app/views/video-details/video-details.component.ts
Labels: enhancement

#27 fix breadcrum and navigation
  src/app/app-routing.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/player-card/player-card.component.ts
  src/app/interfaces/breadcrumbs.interface.ts
  src/app/interfaces/player.interface.ts
  src/app/models/player.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.html
  src/app/views/video-details/video-details.component.ts
  src/assets/players.json
Labels: enhancement

#30 add environment andd encrypt closes #29
  angular.json
  package-lock.json
  package.json
  src/app/services/request-player.service.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: enhancement

#26 Feature/not found view
  src/app/app-routing.module.ts
  src/app/components/footer/footer.component.scss
  src/app/styles/mixin.styles.scss
  src/app/views/not-found/not-found.component.html
  src/app/views/not-found/not-found.component.scss
  src/app/views/not-found/not-found.component.ts
  src/assets/page-notFound.png
Labels: enhancement

#32 create breadcrumb view closes #31
  README.md
  src/app/app-routing.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.scss
  src/app/components/footer/footer.component.scss
  src/app/components/stats/stats.component.scss
  src/app/components/stats/stats.component.ts
  src/app/interfaces/request-players.interface.ts
  src/app/pipes/safe-url.pipe.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.scss
  src/styles.scss
Labels: enhancement

#33 add logger for console
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/breadcrumbs/breadcrumbs.component.scss
  src/app/components/player-card/player-card.component.html
  src/app/components/player-card/player-card.component.scss
  src/app/components/video-card/video-card.component.html
  src/app/components/video-card/video-card.component.scss
  src/app/components/video-card/video-card.component.spec.ts
  src/app/components/video-card/video-card.component.ts
  src/app/models/log-levels.spec.ts
  src/app/models/log-levels.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/logger.service.spec.ts
  src/app/services/logger.service.ts
  src/app/services/request-player.service.ts
  src/app/views/video-details/video-details.component.scss
Labels: enhancement

#36 add developer control closes #35
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.ts
  src/app/services/global-error-handler.service.spec.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/logger.service.ts
  src/app/views/home/home.component.ts
  src/app/views/player-details/player-details.component.scss
  src/app/views/player-details/player-details.component.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: enhancement

#37 Develop
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.ts
  src/app/services/global-error-handler.service.spec.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/logger.service.ts
  src/app/views/home/home.component.ts
  src/app/views/player-details/player-details.component.scss
  src/app/views/player-details/player-details.component.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: production

#38 update readme
  README.md
Labels: documentation

#39 commit dev mode
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.ts
Labels: test

#41 Develop
  README.md
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.ts
Labels: test

#42 Clean code
  .eslintrc.json
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.html
  src/app/components/player-card/player-card.component.ts
  src/app/components/stats/stats.component.ts
  src/app/interfaces/breadcrumbs.interface.ts
  src/app/pipes/safe-url.pipe.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/request-player.service.ts
  src/app/views/home/home.component.ts
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.ts
Labels: enhancement

#43 Develop
  .eslintrc.json
  src/app/app.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.html
  src/app/components/player-card/player-card.component.ts
  src/app/components/stats/stats.component.ts
  src/app/interfaces/breadcrumbs.interface.ts
  src/app/pipes/safe-url.pipe.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/request-player.service.ts
  src/app/views/home/home.component.ts
  src/app/views/player-details/player-details.component.html
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.ts
Labels: enhancement

#45 Features/improve routing
  src/app/app-routing.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/interfaces/request-players.interface.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/lenguage.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: enhancement

#46 fix error on player_card
  src/app/components/player-card/player-card.component.html
Labels: bug

#47 Develop
  src/app/app-routing.module.ts
  src/app/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/header/header.component.ts
  src/app/components/player-card/player-card.component.html
  src/app/components/player-card/player-card.component.ts
  src/app/components/stats/stats.component.ts
  src/app/interfaces/request-players.interface.ts
  src/app/services/breadcrumbs.service.ts
  src/app/services/global-error-handler.service.ts
  src/app/services/lenguage.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.ts
  src/app/views/video-details/video-details.component.ts
  src/assets/intl/en.json
  src/assets/intl/es.json
Labels: enhancement

#48 clean console logs
  src/app/services/breadcrumbs.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.ts
Labels: bug

#49 Develop
  src/app/services/breadcrumbs.service.ts
  src/app/services/request-player.service.ts
  src/app/views/player-details/player-details.component.ts
Labels: enhancement
